"use client";

import type { CardFormValue } from "@/lib/card-form";
import { Field, Input, Select, TextArea } from "@/components/ui/Form";
import { Panel } from "@/components/ui/Surface";

const sports = ["Basketball", "Football", "Baseball", "Soccer", "Hockey", "TCG", "Other"];
const graders = ["Raw", "PSA", "BGS", "SGC", "CGC"];

export type CardFieldSection = "identity" | "grading" | "value";

export default function CardFields({ value, onChange, disabled = false, sections = ["identity", "grading", "value"] }: { value: CardFormValue; onChange: (value: CardFormValue) => void; disabled?: boolean; sections?: CardFieldSection[] }) {
  const set = (key: keyof CardFormValue, next: string) => onChange({ ...value, [key]: next });
  return <>
    {sections.includes("identity") && <Panel className="space-y-6 p-5 md:p-7"><div><p className="eyebrow">Identity</p><h2 className="heading-2 mt-2">Card record</h2></div><Field label="Player or subject"><Input disabled={disabled} value={value.playerName} onChange={(event) => set("playerName", event.target.value)} placeholder="e.g. Michael Jordan"/></Field><div className="grid gap-6 sm:grid-cols-2"><Field label="Sport"><Select disabled={disabled} value={value.sport} onChange={(event) => set("sport", event.target.value)}>{sports.map((item) => <option key={item}>{item}</option>)}</Select></Field><Field label="Team" optional><Input disabled={disabled} value={value.team} onChange={(event) => set("team", event.target.value)} placeholder="Chicago Bulls"/></Field><Field label="Year" optional><Input disabled={disabled} value={value.year} onChange={(event) => set("year", event.target.value)} placeholder="2025 or 2025-26"/></Field><Field label="Brand" optional><Input disabled={disabled} value={value.brand} onChange={(event) => set("brand", event.target.value)} placeholder="Fleer"/></Field><Field label="Set" optional><Input disabled={disabled} value={value.setName} onChange={(event) => set("setName", event.target.value)} placeholder="Premier"/></Field><Field label="Card number" optional><Input disabled={disabled} value={value.cardNumber} onChange={(event) => set("cardNumber", event.target.value)} placeholder="57"/></Field><Field label="Parallel or variant" optional><Input disabled={disabled} value={value.parallel} onChange={(event) => set("parallel", event.target.value)} placeholder="Silver Prizm"/></Field><Field label="Serial number" optional><Input disabled={disabled} value={value.serialNumber} onChange={(event) => set("serialNumber", event.target.value)} placeholder="23/99"/></Field><Field label="Rookie card" optional><Select disabled={disabled} value={value.rookieCard} onChange={(event) => set("rookieCard", event.target.value)}><option value="unknown">Unknown</option><option value="yes">Yes</option><option value="no">No</option></Select></Field></div></Panel>}
    {sections.includes("grading") && <Panel className="space-y-6 p-5 md:p-7"><div><p className="eyebrow">Certification</p><h2 className="heading-2 mt-2">Grade and provenance</h2></div><fieldset disabled={disabled} className="space-y-5"><legend className="text-xs font-semibold uppercase tracking-[0.13em] text-[var(--text-secondary)]">Format</legend><div className="grid grid-cols-2 gap-3"><button type="button" aria-pressed={value.grader === "Raw"} onClick={() => onChange({ ...value, grader: "Raw", grade: "" })} className={`min-h-12 touch-manipulation rounded-lg border px-4 text-sm font-semibold ${value.grader === "Raw" ? "border-[var(--gold-primary)] bg-[color-mix(in_srgb,var(--gold-primary)_10%,transparent)] text-[var(--gold-primary)]" : "border-[var(--border-subtle)] text-[var(--text-secondary)]"}`}>Raw</button><button type="button" aria-pressed={value.grader !== "Raw"} onClick={() => value.grader === "Raw" && onChange({ ...value, grader: "PSA", grade: "" })} className={`min-h-12 touch-manipulation rounded-lg border px-4 text-sm font-semibold ${value.grader !== "Raw" ? "border-[var(--gold-primary)] bg-[color-mix(in_srgb,var(--gold-primary)_10%,transparent)] text-[var(--gold-primary)]" : "border-[var(--border-subtle)] text-[var(--text-secondary)]"}`}>Graded</button></div><Field label="Visible condition" optional helper="For raw cards, record the condition visible in the image."><Input disabled={disabled} value={value.condition} onChange={(event) => set("condition", event.target.value)} placeholder="Near Mint"/></Field>{value.grader !== "Raw" && <div className="grid gap-6 sm:grid-cols-2"><Field label="Grading company"><Select disabled={disabled} value={value.grader} onChange={(event) => set("grader", event.target.value)}>{graders.filter((item) => item !== "Raw").map((item) => <option key={item}>{item}</option>)}</Select></Field><Field label="Grade"><Input disabled={disabled} value={value.grade} onChange={(event) => set("grade", event.target.value)} placeholder="10"/></Field></div>}</fieldset></Panel>}
    {sections.includes("value") && <Panel className="space-y-6 p-5 md:p-7"><div><p className="eyebrow">Collection status</p><h2 className="heading-2 mt-2">Value and notes</h2></div><div className="grid gap-6 sm:grid-cols-2"><Field label="Estimated value" optional helper="Enter a value in US dollars."><Input disabled={disabled} inputMode="decimal" value={value.estimatedValue} onChange={(event) => set("estimatedValue", event.target.value)} placeholder="$0"/></Field><Field label="Status"><Select disabled={disabled} value={value.status} onChange={(event) => set("status", event.target.value)}><option value="personal_collection">Personal collection</option><option value="for_sale">For sale</option><option value="for_trade">For trade</option><option value="wishlist">Wishlist</option><option value="watchlist">Watchlist</option><option value="sold">Sold</option></Select></Field></div><Field label="Curator notes" optional><TextArea disabled={disabled} value={value.notes} onChange={(event) => set("notes", event.target.value)} placeholder="Record provenance, condition, or the story behind this card."/></Field></Panel>}
  </>;
}
