import { Panel } from "@/components/ui/Surface";
import type { CardSalesResponse } from "@/lib/card-intelligence";

export default function RecentSalesPanel({ data, loading, error }: { data: CardSalesResponse | null; loading: boolean; error?: string }) {
  return <Panel className="p-5"><p className="eyebrow">Market tools</p><h3 className="heading-3 mt-2">Recent sales pending</h3>
    {loading ? <p className="mt-3 text-sm text-[var(--text-secondary)]">Checking whether market data is connected…</p> : error ? <p className="mt-3 text-sm text-[var(--status-error)]">{error}</p> : data?.available && data.sales.length ? <div className="mt-4 space-y-4"><div className="grid grid-cols-2 gap-3"><div className="rounded-lg border border-[var(--border-subtle)] p-3"><span className="text-xs text-[var(--text-tertiary)]">Average</span><strong className="mt-1 block tabular-nums">${Number(data.average || 0).toLocaleString()}</strong></div><div className="rounded-lg border border-[var(--border-subtle)] p-3"><span className="text-xs text-[var(--text-tertiary)]">Median</span><strong className="mt-1 block tabular-nums">${Number(data.median || 0).toLocaleString()}</strong></div></div>{data.sales.slice(0, 5).map((sale) => <a key={`${sale.source}-${sale.url}`} href={sale.url} target="_blank" rel="noreferrer" className="block rounded-lg border border-[var(--border-subtle)] p-3"><span className="font-semibold">{sale.price} {sale.currency}</span><span className="mt-1 block text-xs text-[var(--text-tertiary)]">{sale.source} · {sale.sale_type.replaceAll("_", " ")} · {sale.sale_date}</span><span className="mt-1 block text-xs text-[var(--text-tertiary)]">{[sale.condition, sale.grade_company, sale.grade].filter(Boolean).join(" · ") || "Condition not listed"}</span></a>)}</div> : <p className="mt-3 text-sm leading-6 text-[var(--text-tertiary)]">{data?.message || "Recent sales lookup is not connected yet."}</p>}
    <p className="mt-4 border-t border-[var(--border-subtle)] pt-3 text-[11px] uppercase tracking-[0.12em] text-[var(--text-tertiary)]">Pending integration, not an appraisal.</p>
  </Panel>;
}
